### ISSUE TITLE
Ambient Occlusion artifacts in first person using OR 7.1

### ISSUE THREAD

**Issue by summercatmeow** [XJDHDR/game-mods#1] opened 2020-03-11 03:16 UTC
Upon loading a new cell or entering first person mode, the first frame of rendered ambient occlusion will get stuck on the camera leaving a shadowed outline of whatever you were looking at. Entering third person will remove the ghosted AO, however reentering first person will create a new one.

Occurs with Oblivion Reloaded 7.1 with Ambient Occlusion effect enabled with default AO shader settings. 

Disabling Enhanced Camera resolves the issue.

**Comment by XJDHDR** [comment] 2020-04-19 02:49
Good day Bobertob

Sorry for the late reply. Unfortunately, I'm busy with college currently so I'm not sure when I will be able to look into this.

There is a discussion going on about this in the TES Reloaded forum here: https://tesreloaded.com/thread/2083/7-enhanced-camera?page=3
Alenet seems to believe that there is a conflict between Enhanced Camera and OR's depth buffer logic.

In the meantime, there are two workarounds available if you want to use my Enhanced Camera DLL with OR:

- Downgrade Oblivion Reloaded to version 7.0, or
- Disable the post-processing effects that are causing problems (under the [Effects] key in OblivionReloaded.ini). I believe Ambient Occlusion, God Rays, Underwater and possibly Depth of Field have been identified as problematic effects.

**Comment by llde** [comment] 2020-04-26 23:03
Hi. @Bobertob 
The issue should be resolved in this OR DLL. 
https://github.com/llde/TES-Reloaded-Source-NEW/releases/tag/8.0b4UN

Can you try?

**Comment by XJDHDR** [comment] 2020-04-28 17:29
@llde 
This is a pleasant surprise. I tested your DLL and I didn't see this problem in my brief testing with AO and Underwater enabled. If I can get any further confirmation from @Bobertob or others, I can close this one.

**Comment by XJDHDR** [comment] 2020-05-14 09:28
I just saw that a bunch of people have confirmed in the linked thread that this has been fixed.

**Closed as completed by XJDHDR** 2020-05-14 09:28 UTC
Labels: bug, fixed
